routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use App\Http\Controllers\WEB\Admin\AdminOrderController;
use App\Http\Controllers\WEB\Admin\SettingsController;
use App\Http\Controllers\WEB\Admin\TermsConditionController;
use App\Http\Controllers\WEB\Admin\AdminMessageController;
use App\Http\Controllers\WEB\Auth\AdminLoginController;
use App\Http\Controllers\WEB\Admin\DashboardController;
use App\Http\Controllers\WEB\Admin\CustomersController;
use App\Http\Controllers\WEB\Admin\CountryController;
use App\Http\Controllers\WEB\Admin\StateController;
use App\Http\Controllers\WEB\Admin\CityController;
use App\Http\Controllers\WEB\Admin\GalleryController;
use App\Http\Controllers\WEB\Admin\SubscriberController;
use App\Http\Controllers\WEB\Admin\TestimonialController;
use App\Http\Controllers\WEB\Admin\LanguageController;
use App\Http\Controllers\WEB\Admin\FAQController;
use App\Http\Controllers\WEB\Admin\ContactUsController;
use App\Http\Controllers\WEB\Admin\SliderController;
use App\Http\Controllers\WEB\Admin\AdminProfileController;
use App\Http\Controllers\WEB\Admin\FooterController;
use App\Http\Controllers\WEB\Admin\FooterSocialLinkController;
use App\Http\Controllers\WEB\Admin\AboutUsController;
use App\Http\Controllers\WEB\Admin\FrontendLanguageController;
use App\Http\Controllers\WEB\Admin\PrivecyController;
use App\Http\Controllers\WEB\Admin\SEOSetupController;
use App\Http\Controllers\WEB\Admin\PaymentController as AdminPaymentController;
use App\Http\Controllers\WEB\Admin\EmailConfigController;
use App\Http\Controllers\WEB\User\Auth\LoginController;
use App\Http\Controllers\WEB\Admin\CategoryController;
use App\Http\Controllers\WEB\Admin\OptionalItemController;
use App\Http\Controllers\WEB\Admin\ProductController;
use App\Http\Controllers\WEB\Admin\BlogController;
use App\Http\Controllers\WEB\Admin\BlogCategoryController;
use App\Http\Controllers\WEB\Admin\FAQAboutController;
use App\Http\Controllers\WEB\Admin\MobileAppController;
use App\Http\Controllers\WEB\Admin\CraftingProcessController;
use App\Http\Controllers\WEB\Admin\PromotionController;
use App\Http\Controllers\WEB\Admin\SectionController;
use App\Http\Controllers\WEB\Admin\EmptyImageController;
use App\Http\Controllers\WEB\Admin\ProductReviewController;
use App\Http\Controllers\WEB\Admin\CouponController;
use App\Http\Controllers\WEB\Admin\ShippingController;
use App\Http\Controllers\WEB\Admin\TimeSlotController;
use App\Http\Controllers\WEB\Admin\OrderController;
use App\Http\Controllers\WEB\Admin\DeliveryAreaController;


use App\Http\Controllers\WEB\Auth\UserLoginController;
use App\Http\Controllers\WEB\Auth\ForgotPasswordController;

use App\Http\Controllers\WEB\User\DashboardController as UserDashboardController;

use App\Http\Controllers\WEB\Frontend\HomeController;
use App\Http\Controllers\WEB\Frontend\WishlistController;
use App\Http\Controllers\WEB\Frontend\CartController;
use App\Http\Controllers\WEB\Frontend\CheckoutController;
use App\Http\Controllers\WEB\Frontend\PaymentController;

use App\Models\setting as Setting;

Route::group(['middleware' => ['XSS']], function () {

    Route::group(['middleware' => ['HtmlSpecialchars']], function () {
        // Frontend Pages Routes....
        Route::get('/lang/{lang_code}', [HomeController::class,'setLanguage'])->name('set.language');
        Route::get('/change/theme/{theme}', [CartController::class,'changeTheme'])->name('change.fontend.theme');
        Route::get('/', [HomeController::class,'index'])->name('index');
        Route::get('/menu', [HomeController::class,'menu'])->name('menu');
        Route::get('/menu/{slug}', [HomeController::class,'menuDetils'])->name('menu-detils');
        Route::get('/about-us', [HomeController::class,'about'])->name('about');
        Route::get('/contact-us', [HomeController::class,'contact'])->name('contact');
        Route::get('/blog', [HomeController::class,'blog'])->name('blog');
        Route::get('/blog/{slug}', [HomeController::class,'blogDetils'])->name('blog-detils');
        Route::get('/wishlist', [HomeController::class,'wishList'])->name('wishlist');
        Route::get('/cartlist', [HomeController::class,'cartList'])->name('cartlist');
        Route::post('/newslatter', [HomeController::class,'newsLatter'])->name('newslatter');
        Route::get('/newsletter/verify/email', [HomeController::class,'newsletter_verify_email'])->name('newsletter.verify.email');
        Route::post('/contact/message', [HomeController::class,'contactMessage'])->name('contact.message');
        Route::post('/product/review', [HomeController::class,'ProductReview'])->name('product.review');
        Route::post('/blog/comment', [HomeController::class,'blogComment'])->name('user.blog.comment');
        Route::get('/search', [HomeController::class,'search'])->name('search');
        Route::get('/blog-search', [HomeController::class,'blogSearch'])->name('blog.search');
        Route::get('/terms-of-service', [HomeController::class,'tremsOfServices'])->name('trems.of.service');
        Route::get('/privacy-policy', [HomeController::class,'privacyPolicy'])->name('privacy.policy');

        Route::get('/cart-view', [CartController::class,'view'])->name('wishlist.index');
        Route::get('/add-to-cart/{product}', [CartController::class,'addToCart'])->name('cart.add');
        Route::post('/cart/add', [CartController::class,'addProduct'])->name('cart.add.detils');
        Route::get('/cart', [CartController::class,'index'])->name('cart.index');
        Route::get('/cart/remove/{product_id}', [CartController::class,'removeProduct'])->name('cart.remove');
        Route::get('/cart/increment/{product_id}', [CartController::class,'cartIncrement'])->name('cart.increment');
        Route::get('/cart/decrement/{product_id}', [CartController::class,'cartDecremet'])->name('cart.decrement');
        Route::post('/cart/update/{product_id}', [CartController::class,'cartUpdate'])->name('update.order.cart');

        Route::get('/wishlist/add', [WishlistController::class,'index'])->name('wishlist.index');
        Route::get('/wishlist/add/{product_id}',[WishlistController::class,'add'])->name('wishlist.add');
        Route::get('/wishlist/remove/{product_id}',[WishlistController::class,'remove']) ->name('wishlist.remove');

        Route::get('/checkout', [CheckoutController::class,'delivery'])->name('checkout');
        Route::get('/pickUp', [CheckoutController::class,'pickUp'])->name('pickup');
        Route::get('/inResturent', [CheckoutController::class,'inResturent'])->name('inresturent');
        Route::post('/process/order', [CheckoutController::class,'processOrder'])->name('process.order');
        Route::post('/apply-coupon', [CheckoutController::class,'applyCoupon'])->name('apply.coupon');
        Route::get('/select/payment/method', [CheckoutController::class,'selectPayment'])->name('select.payment.method');
        Route::post('/checkout/order', [CheckoutController::class,'checkOut'])->name('checkout.order');

        // User Login Routes.....
        Route::group(['middleware'=>'guest'],function () {
            Route::get('/login', [UserLoginController::class,'index'])->name('login');
            Route::post('/login', [UserLoginController::class,'login'])->name('login');
            Route::get('/verify/user/email', [UserLoginController::class,'verify_user_email'])->name('verify.user.email');
            Route::get('/register', [UserLoginController::class,'registerView'])->name('register');
            Route::post('/register', [UserLoginController::class,'register'])->name('register');
            Route::get('/forgot/password', [UserLoginController::class,'Forgot'])->name('forgot.password.user');
            Route::post('/forgot/password', [UserLoginController::class,'ForgotPassword'])->name('forgot.password.user');
            Route::get('/reset/password', [UserLoginController::class,'ResetPassword'])->name('reset.password.user');
            Route::post('/set/password', [UserLoginController::class,'SetPassword'])->name('reset.password.user');
        });

        // User Page Routes
        Route::group(['middleware' => 'auth', 'prefix' => 'user'], function () {
            Route::get('/logout', [UserLoginController::class, 'LogOut'])->name('logout');

            Route::get('/dashboard', [UserDashboardController::class, 'UserDashboard'])->name('user.dashboard');
            Route::get('/edit-profile', [UserDashboardController::class, 'UserProfile'])->name('user.edit.profile');
            Route::get('/address', [UserDashboardController::class, 'address'])->name('user.address');
            Route::get('/address/{id}', [UserDashboardController::class, 'addressEdit'])->name('user.address.edit');
            Route::post('/address/update/{id}', [UserDashboardController::class, 'addressUpdate'])->name('user.address.upadate');
            Route::post('/add/new/address', [UserDashboardController::class, 'addNewAddress'])->name('add.new.address');
            Route::get('/remove/address/{id}', [UserDashboardController::class, 'removeAddress'])->name('remove.address');
            Route::get('/order', [UserDashboardController::class, 'order'])->name('user.order');
            Route::get('/order/last/week', [UserDashboardController::class, 'orderWeekly'])->name('user.order.last.week');
            Route::get('/order/detils/{id}', [UserDashboardController::class, 'orderDetils'])->name('user.order.detils');
            Route::get('/wishlist', [UserDashboardController::class, 'wishlist'])->name('user.wishlist');
            Route::get('/review', [UserDashboardController::class, 'review'])->name('user.review');
            Route::get('/change-password', [UserDashboardController::class, 'changePassword'])->name('user.change.password');
            Route::post('/profile/update/{id}', [UserDashboardController::class, 'UpdateProfile'])->name('user.update.profile');

app/Models/Slider.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Session;

class Slider extends Model
{
    use HasFactory;

    public function translate_slider()
    {
        return $this->belongsTo(TranslateSlider::class,'id','slider_id')->where('lang_code','en');
    }
    public function translate_slider_lang()
    {
        if(Session::get('front_lang')){
            $lang_code = Session::get('front_lang');
        }
        else{
            $lang_key = \App\Models\Setting::where('id', 1)->value('lang_key');
            $lang_code = $lang_key ?? 'en';
        }

        return $this->belongsTo(TranslateSlider::class,'id','slider_id')->where('lang_code',$lang_code);;
    }


    protected $appends = ['title'];
    protected $hidden = ['translate_slider_lang'];

    public function getTitleAttribute()
    {
       return $this->translate_slider_lang->title;

    }
    public function getDescriptionAttribute()
    {
       return $this->translate_slider_lang->title;

    }
}

app/Http/Controllers/WEB/Frontend/WishlistController.php
<?php

namespace App\Http\Controllers\WEB\Frontend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Wishlist;

class WishlistController extends Controller
{
    public function index()
    {
        $wishlist = session('wishlist', []);

        return $wishlist;
    }

    public function add($product_id)
    {

        if (auth()->check()) {
            $user_id = auth()->user()->id;
            if (!Wishlist::where('user_id', $user_id)->where('product_id', $product_id)->exists()) {
                Wishlist::create(['user_id' => $user_id, 'product_id' => $product_id]);

                $message = trans('translate.Item added to wishlist');
                $notification = ['message' => $message, 'alert-type' => 'success'];
            } else {
                $message = trans('translate.Item already added in wishlist');
                $notification = ['message' => $message, 'alert-type' => 'error'];
            }
        } else {
            $message = trans('translate.You have to login first');
            $notification = ['message' => $message, 'alert-type' => 'error'];
            return redirect()->route('login')->with($notification);
        }

        return redirect()->back()->with($notification);

    }

    public function remove($product_id)
    {
        if (auth()->check()) {
            $user_id = auth()->user()->id;
            Wishlist::where('user_id', $user_id)
                    ->where('product_id', $product_id)
                    ->delete();
            $message = trans('translate.Item removed successfully');
            $notification = ['message' => $message, 'alert-type' => 'success'];
        } else {
            $message = trans('translate.You have to login first');
            $notification = ['message' => $message, 'alert-type' => 'error'];
        }

        return redirect()->back()->with($notification);
    }
}

resources/views/Frontend/Pages/privacy_policy.blade.php
@extends('Frontend.Layouts.master')

@section('title')
    <title>{{$setting->app_name}} - {{ __('translate.Privacy Policy') }}</title>
@endsection

@section('content')
<main>

    <!-- banner  -->

    <div class="inner-banner">
        <div class="container">
            <div class="row  ">
                <div class="col-lg-12">
                    <div class="inner-banner-head">
                        <h1>{{ __('translate.Privacy Policy') }}</h1>
                    </div>

                    <div class="inner-banner-item">
                        <div class="left">
                            <a href="{{route('index')}}">{{ __('translate.Home') }}</a>
                        </div>
                        <div class="icon">
                            <span>
                                <svg width="24" height="24" viewBox="0 0 24 24" fill="none"
                                    xmlns="http://www.w3.org/2000/svg">
                                    <path d="M10 7L14 12L10 17" stroke="#E5E6EB" stroke-width="2"
                                        stroke-linecap="round" stroke-linejoin="round" />
                                </svg>
                            </span>
                        </div>
                        <div class="left">
                            <span>{{ __('translate.Privacy Policy') }}</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- banner  -->

    <!-- Shopping Cart  start -->
    <section class="shopping-cart-two shopping-cart-address all-details-root ">
        <div class="container">
            {!! clean($privecy->privacy) !!}
        </div>
    </section>

</main>

@endsection

resources/views/Frontend/Pages/terms_of_services.blade.php
@extends('Frontend.Layouts.master')

@section('title')
    <title>{{$setting->app_name}} - {{ __('translate.Terms and Conditions') }}</title>
@endsection

@section('content')
<main>

    <!-- banner  -->

    <div class="inner-banner">
        <div class="container">
            <div class="row  ">
                <div class="col-lg-12">
                    <div class="inner-banner-head">
                        <h1>{{ __('translate.Terms and Conditions') }}</h1>
                    </div>

                    <div class="inner-banner-item">
                        <div class="left">
                            <a href="{{route('index')}}">{{ __('translate.Home') }}</a>
                        </div>
                        <div class="icon">
                            <span>
                                <svg width="24" height="24" viewBox="0 0 24 24" fill="none"
                                    xmlns="http://www.w3.org/2000/svg">
                                    <path d="M10 7L14 12L10 17" stroke="#E5E6EB" stroke-width="2"
                                        stroke-linecap="round" stroke-linejoin="round" />
                                </svg>
                            </span>
                        </div>
                        <div class="left">
                            <span>{{ __('translate.Terms and Conditions') }}</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- banner  -->



    <!-- Shopping Cart  start -->



    <section class="shopping-cart-two shopping-cart-address all-details-root ">
        <div class="container">
            {!! clean($trems_condation->termsandcondition) !!}
        </div>
    </section>

</main>

@endsection

resources/views/Frontend/Pages/wishlist.blade.php
@extends('Frontend.Layouts.master')

@section('title')
    <title>{{$setting->app_name}} - {{ __('translate.WishList') }}</title>
@endsection

@section('content')
<main>

    <!-- banner  -->

    <div class="inner-banner">
        <div class="container">
            <div class="row  ">
                <div class="col-lg-12">
                    <div class="inner-banner-head">
                        <h1>{{ __('translate.WishList') }}</h1>
                    </div>

                    <div class="inner-banner-item">
                        <div class="left">
                            <a href="{{route('index')}}">{{ __('translate.Home') }}</a>
                        </div>
                        <div class="icon">
                            <span>
                                <svg width="24" height="24" viewBox="0 0 24 24" fill="none"
                                    xmlns="http://www.w3.org/2000/svg">
                                    <path d="M10 7L14 12L10 17" stroke="#E5E6EB" stroke-width="2"
                                        stroke-linecap="round" stroke-linejoin="round" />
                                </svg>
                            </span>
                        </div>
                        <div class="left">
                            <span>{{ __('translate.WishList') }}</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- banner  -->



    <!-- dashboard  start -->


    <section class="dashboard">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 col-md-8 ">
                    <div class="row">
                        @foreach ($product as $product)
                            <div class="col-lg-6 col-md-12  popular-item-mt-30px" data-aos="fade-up">
                                <div class="popular-item-box">
                                    <div class="popular-item-box-img">
                                        <img src="{{asset($product['tumb_image'])}}" alt="thumb">
                                        <div class="popular-item-box-img-overlay">
                                        </div>
                                    </div>

                                    <div class="popular-inner-box">
                                        <a href="{{route('menu-detils',$product->slug)}}">
                                            <div class="popular-item-box-text">
                                                <h3>{{$product->name}}</h3>
                                            </div>
                                        </a>
                                        @foreach(json_decode($product->specifaction, true) as $name)
                                            <div class="popular-inner-item">
                                                <div class="icon">
                                                    <span><svg width="20" height="20" viewBox="0 0 20 20" fill="none"
                                                        xmlns="http://www.w3.org/2000/svg">
                                                        <g clip-path="url(#clip0_304_21999)">
                                                            <path
                                                                d="M6.66699 10.0013L8.77923 11.9023C9.13881 12.2259 9.69748 12.1764 9.99449 11.7945L13.3337 7.5013M10.0003 18.3346C14.6027 18.3346 18.3337 14.6037 18.3337 10.0013C18.3337 5.39893 14.6027 1.66797 10.0003 1.66797C5.39795 1.66797 1.66699 5.39893 1.66699 10.0013C1.66699 14.6037 5.39795 18.3346 10.0003 18.3346Z"
                                                                stroke="#FE724C" stroke-width="1.5"
                                                                stroke-linecap="round" stroke-linejoin="round"></path>
                                                        </g>
                                                    </svg></span>
                                                </div>

                                                <div class="text">
                                                    <h5>{{$name}}</h5>
                                                </div>
                                            </div>
                                        @endforeach


                                        <div class="popular-inner-item-btm">
                                            <div class="text">
                                                <h3>{{$setting->currency_icon}}{{$product->price}}</h3>
                                            </div>


                                            <div class="popular-inner-item-btn">
                                                <a href="{{route('wishlist.remove',$product->id)}}" class="main-btn-five">
                                                    <span>
                                                        <svg width="17" height="20" viewBox="0 0 17 20" fill="none" xmlns="http://www.w3.org/2000/svg">
                                                            <path fill-rule="evenodd" clip-rule="evenodd" d="M5.834 0.890599C6.20493 0.334202 6.8294 0 7.4981 0H9.35737C10.0261 0 10.6505 0.334202 11.0215 0.8906L11.9277 2.25H15.6777C16.0919 2.25 16.4277 2.58579 16.4277 3C16.4277 3.41421 16.0919 3.75 15.6777 3.75H1.17773C0.763521 3.75 0.427734 3.41421 0.427734 3C0.427734 2.58579 0.763521 2.25 1.17773 2.25H4.92773L5.834 0.890599ZM11.4277 20H5.42773C3.2186 20 1.42773 18.2091 1.42773 16V5H15.4277V16C15.4277 18.2091 13.6369 20 11.4277 20ZM6.42773 8.25C6.84195 8.25 7.17773 8.58579 7.17773 9V16C7.17773 16.4142 6.84195 16.75 6.42773 16.75C6.01352 16.75 5.67773 16.4142 5.67773 16L5.67773 9C5.67773 8.58579 6.01352 8.25 6.42773 8.25ZM10.4277 8.25C10.8419 8.25 11.1777 8.58579 11.1777 9V16C11.1777 16.4142 10.8419 16.75 10.4277 16.75C10.0135 16.75 9.67774 16.4142 9.67773 16V9C9.67773 8.58579 10.0135 8.25 10.4277 8.25Z" fill="white"></path>
                                                        </svg>
                                                    </span>
                                                    {{ __('translate.Remove') }}
                                                </a>
                                                    <button type="button" data-bs-toggle="modal"
                                                        data-bs-target="#exampleModal{{ $product['id'] }}" class="main-btn-five">
                                                        <span>
                                                            <svg width="24" height="24" viewBox="0 0 24 24" fill="none"
                                                                xmlns="http://www.w3.org/2000/svg">
                                                                <path
                                                                    d="M6 4H18C20.2091 4 22 5.79086 22 8V13C22 15.2091 20.2091 17 18 17H10C7.79086 17 6 15.2091 6 13V4ZM6 4C6 2.89543 5.10457 2 4 2H2"
                                                                    stroke-width="1.5" stroke-linecap="round"
                                                                    stroke-linejoin="round"></path>
                                                                <path
                                                                    d="M11 20.5C11 21.3284 10.3284 22 9.5 22C8.67157 22 8 21.3284 8 20.5C8 19.6716 8.67157 19 9.5 19C10.3284 19 11 19.6716 11 20.5Z"
                                                                    stroke-width="1.5"></path>
                                                                <path
                                                                    d="M20 20.5C20 21.3284 19.3284 22 18.5 22C17.6716 22 17 21.3284 17 20.5C17 19.6716 17.6716 19 18.5 19C19.3284 19 20 19.6716 20 20.5Z"
                                                                    stroke-width="1.5"></path>
                                                                <path d="M14 8L14 13" stroke-width="1.5"
                                                                    stroke-linecap="round" stroke-linejoin="round">
                                                                </path>
                                                                <path d="M16.5 10.5L11.5 10.5" stroke-width="1.5"
                                                                    stroke-linecap="round" stroke-linejoin="round">
                                                                </path>
                                                            </svg>
                                                        </span>
                                                        {{ __('translate.Add to Cart') }}
                                                </button>
                                            </div>
                                        </div>

                                    </div>


                                </div>
                            </div>
                        @endforeach

                    </div>
                </div>
            </div>
        </div>
    </section>



    <!-- dashboard end  -->


    <!-- Restaurant part-start -->
    @if($setting->app_visibility == 1)
    <section class="restaurant">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-lg-6">
                    <div class="restaurant-taitel">
                        <h2>{{ $app->titel }}</h2>

                        <h4>{!! clean($app->description) !!}</h4>
                    </div>

                    <div class="restaurant-taitel-btn">
                        <a href="{{ $app->play_store }}" class="paly-bg" > <span>
                      
                            </span> {{ __('translate.Play Store') }}</a>
                        <a href="{{ $app->i_store }}" class=" restaurant-taitel-btn-two"> <span>
                              
                            </span> {{ __('translate.App Store') }}</a>
                    </div>
                </div>
                <div class="col-lg-6" data-aos="fade-left">
                    <div class="restaurant-img-main">
                        <div class="restaurant-img">
                                <img src="{{asset($app->image)}}" alt="img">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    @endif
    <!-- Restaurant part-end -->
</main>

@endsection